name: cron
on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  crawl:
    runs-on: ubuntu-latest
    container: python
    steps:
      - uses: actions/checkout@v2
      - run: pip install .
      - run: scrapy crawl milt-nega-inf
